### ISSUE TITLE
fix Living vector for the CFRE models

### ISSUE THREAD

**Issue by borretts** [SEELab/enaR#107]
The living vector is incorrect in these two BGC models.

**Comment by borretts** [comment]
@MKLau -- can you remind me what we need to do to both correct models in our library and to add models to the library?

**Comment by MKLau** [comment]
Hey Stuart, here's a how-to that I added to the enaR_development wiki. Let me know if you run into issues. 

@borretts

**Comment by borretts** [comment]
done.
