### ISSUE TITLE
enaUtility: change eigen check to match enaMTI

### ISSUE THREAD

**Issue by borretts** [SEELab/enaR#172]
eigen.check behaves differently in these two functions.  If eigen.check = TRUE and the dominant eigenvalue of D is over 1, this stops enaUtility from running at all.  In contrast, if the same conditions are true in enaMTI the function runs and returns all but the integral matrix that requires the inappropriate inverse.  I recommend we change enaUtility to follow the same logic.

**Comment by MKLau** [comment]
@borretts 

Have you fixed this already?

**Comment by borretts** [comment]
I believe this is fixed.
