### ISSUE TITLE
read.enam is not correctly capturing the model flows

### ISSUE THREAD

**Issue by borretts** [SEELab/enaR#181]
Discovered by Ursula Scharler.

**Comment by borretts** [comment]
I have fixed the function and pushed the fix to the beta branch. 

The bug was caused by the change to storing the flows as edge weights.  While we fixed this data storage issue inside the pack function, the read.enam function was not using pack -- it had its own code to build the data object.  I replaced this code to use the pack function, which fixed the problem and I hops should make the code more robust.

**Comment by MKLau** [comment]
Great, thanks for fixing this. It was already listed as a bug (by you I think) sometime last year.

On May 3, 2016, at 3:14 PM, borretts <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #181<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SEELab_enaR_issues_181&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=yYM9bdhQa7fj0pqtCBPxMvjOe6gKXC-k_OhnGcaB0ZI&m=Ad9SpDwL179YtIz-SwBjRldXR1_AXXIw6Ml5iS-j-NM&s=mODRin-96P--Y1xEY6tFu5kck8qyEkuMC1J2Z0tKb38&e=>.
