### ISSUE TITLE
Create a list of features added since 2.9

### ISSUE THREAD

**Issue by MKLau** [SEELab/enaR#189]

**Comment by MKLau** [comment]
Add features that have been finished here:

https://github.com/SEELab/enaR_development/blob/master/feature_list_30.txt

**Comment by borretts** [comment]
This is going to be a very long list!  We have done quite a bit since the last update.

**Comment by borretts** [comment]
Key to remember is that we have moved 
enaUncertainty, Lindeman Plot, and multiple EcoNet functions to feature branches.  

Some key differences since 2.9 include 
- ShannonDiversity function
- Relations.Tables added to enaUtility and enaMTI
- added Ascendency metrics to the ns vector in enaFlow

**Comment by MKLau** [comment]
This is now included in the package repo as CHANGELOG.
