### ISSUE TITLE
Add Total Flows Calculation (Szyrmer & Ulanowicz 1986)

### ISSUE THREAD

**Issue by borretts** [SEELab/enaR#217]
This includes calculations for the input and output total flows, from which they derived the Total Contribution Coefficients and the Total Dependency Coefficients.  These are results returned by both Netwrk 4.2 and EcoPath that are frequently published.  

Kay, Graham, and Ulanowicz (1989) have a nice description of the calculations.

**Comment by borretts** [comment]
I created a new branch TotalFlows to work on this issue.  I have implemented the code as an addition to the enaFlow function.  The code currently returns results for the Cone Springs model that match the results returned by Netwrk as described in Kay & Ulanowicz (1991) (http://people.clas.ufl.edu/ulan/files/Ulan-Kay.pdf).

**Comment by MKLau** [comment]
Great, thanks for getting that done. Should this be for v2.10?
