### ISSUE TITLE
Add keystoneness calculation from Libralato et al. 2006 (https://www.researchgate.net/publication/222673886)

### ISSUE THREAD

**Issue by borretts** [SEELab/enaR#218]
Libralato et al. (2006) introduced a new ENA measure -- keystoneness -- that they claim provides an indication of which species are keystone species.  While I have questions about the measure, it has become popular in part because its included in EcoPath.  Its a simple calculation, so we should add it as a function to enaR.

**Comment by MKLau** [comment]
I'm going to assign this to v3.1 for now. We can move it to 3.0 if we get to it sooner.

**Comment by borretts** [comment]
I should have this done in about 10 minutes.  I had to calculate it recently.

**Comment by borretts** [comment]
It is difficult to check the accuracy of this function as we don't have a good example; however, the calculations ought to be correct.  Our function operates on all nodes in the network, which means that it will provide a keystones value for the non-living resource pools, which may not make sense following a strict definition of keystone species.

**Comment by borretts** [comment]
I have added the function in its own branch (keystoneness).  When I source the new function locally it works as expected.  However, when I load the branch from github, but function does not appear.  I am wondering if its a name space issue.

**Comment by MKLau** [comment]
Ok, I re-assigned it to v2.10

Let's make this the final addition. I'll take a look at it in a bit, add the documentation from the help file to the vignette and merge it into develop. 

I think that the only thing left for v2.10 after that is to finalize the vignette, build and check. As of right now, the develop branch builds and checks perfectly.

**Comment by MKLau** [comment]
@borretts 

Check the outstanding issues assigned to you: https://waffle.io/SEELab/enaRguide

Assign any back to me if you think I can do them.
