### ISSUE TITLE
enaTroAgg Add steady state check to lindeman spine

### ISSUE THREAD

**Issue by MKLau** [SEELab/enaR#227]

**Comment by MKLau** [comment]
I reassigned this to Stuart to see if the appropriate check has been added in some of the changes he's made recently.

**Comment by borretts** [comment]
Dr. Ulanowicz indicated that the cycle analysis does not require the steady-state assumption, but that the Lindeman Spine calculations do require the steady-state assumption (email March 6th).  If the system is not at steady-state, there is some distortion in the results.
