### ISSUE TITLE
Metabolism is mis-spelled in enaModel and enaModelInfo names in v3.0.0

### ISSUE THREAD

**Issue by MKLau** [SEELab/enaR#267]
Hey Stuart, double check the names. I think it's just [103] "Beijing Urban Metablism (C)"             
[104] "Vienna Urban Metablism (C)".

I'd suggest that we submit this with v3.1.

**Comment by borretts** [comment]
I fixed metabolism, removed an errant space after Chesapeake Bay, and removed the latex code from the Sylt-Romo Bight model name.

**Comment by MKLau** [comment]
Great, thanks!
