### ISSUE TITLE
Dead link for vignette on Wiki

### ISSUE THREAD

**Issue by hrdawson** [SEELab/enaR#295]
The link to the vignette (https://cran.r-project.org/web/packages/enaR/vignettes/enaR-vignette.pdf) is dead on the main Wiki page (https://github.com/SEELab/enaR/wiki). It looks like enaR was removed from CRAN on March 2020. Would it be possible to re-post the vignette elsewhere so that it is still accessible?

Thanks!
Hilary Rose

**Comment by MKLau** [comment]
Hi Hilary Rose, the vignette is in the package itself.

You can access via the vignettes directory: e.g., https://github.com/SEELab/enaR/blob/develop/vignettes/enaR-vignette.pdf. 

Cheers!
