### ISSUE TITLE
enaStructure function does not work 

### ISSUE THREAD

**Issue by Yokelison** [SEELab/enaR#296]
> oyster <- force.balance(oyster)
> St <- enaStructure(oyster)
Error in if (class(A) != "matrix") { : the condition has length > 1

enaStructure this function sames cannot work in this situation,  my codes all follow the tutorial

**Comment by borretts** [comment]
Thanks for letting me know.  I will see if I can fix the error shortly.

**Comment by andybeet** [comment]
@borretts Was this fixed with these [commits](https://github.com/SEELab/enaR/commit/2a17e7eb1177b0b22688230f44fcd36e9eee799a) to `master` ? If i run the code posted by  @Yokelison  i do not get an error
